# Generated by Django 4.0.10 on 2024-03-12 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workoutplan_workoutexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('goal_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('achieved_goals', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exercise_duration', models.IntegerField(blank=True, null=True)),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
